GRAMMAR_START_SYMBOL = "program"

GRAMMAR_PRODUCTIONS = [
    ("program", ["statement_list"]),
    ("statement_list", ["statement_list", "statement"]),
    ("statement_list", ["statement"]),
    ("statement", ["declaration"]),
    ("statement", ["assignment"]),
    ("statement", ["if_statement"]),
    ("statement", ["while_statement"]),
    ("statement", ["print_statement"]),
    ("declaration", ["LET", "ID", "ASSIGN", "expression", "SEMICOLON"]),
    ("assignment", ["ID", "ASSIGN", "expression", "SEMICOLON"]),
    (
        "if_statement",
        ["IF", "LPAREN", "expression", "RPAREN", "LBRACE", "statement_list", "RBRACE"],
    ),
    (
        "if_statement",
        [
            "IF",
            "LPAREN",
            "expression",
            "RPAREN",
            "LBRACE",
            "statement_list",
            "RBRACE",
            "ELSE",
            "LBRACE",
            "statement_list",
            "RBRACE",
        ],
    ),
    (
        "while_statement",
        ["WHILE", "LPAREN", "expression", "RPAREN", "LBRACE", "statement_list", "RBRACE"],
    ),
    ("print_statement", ["PRINT", "LPAREN", "expression", "RPAREN", "SEMICOLON"]),
    ("expression", ["equality"]),
    ("equality", ["equality", "EQ", "comparison"]),
    ("equality", ["equality", "NE", "comparison"]),
    ("equality", ["comparison"]),
    ("comparison", ["comparison", "LT", "term"]),
    ("comparison", ["comparison", "GT", "term"]),
    ("comparison", ["comparison", "LE", "term"]),
    ("comparison", ["comparison", "GE", "term"]),
    ("comparison", ["term"]),
    ("term", ["term", "PLUS", "factor"]),
    ("term", ["term", "MINUS", "factor"]),
    ("term", ["factor"]),
    ("factor", ["factor", "TIMES", "primary"]),
    ("factor", ["factor", "DIVIDE", "primary"]),
    ("factor", ["factor", "MODULO", "primary"]),
    ("factor", ["primary"]),
    ("primary", ["LPAREN", "expression", "RPAREN"]),
    ("primary", ["NUMBER"]),
    ("primary", ["ID"]),
]
